# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'seed.' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seed.

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

#Facebook
pod 'FBSDKLoginKit'

#Facebook
pod 'GoogleSignIn'

pod 'MessageKit'
pod 'JGProgressHUD'#progress bar
pod 'SDWebImage' #image loading capability. handles caching image


  target 'seed.Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'seed.UITests' do
    # Pods for testing
  end

end
